import Link from 'next/link';
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //get all of our pages
  const pages = await getPages();


  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-canter justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-blue-400 via-pink-500 to-yellow-500 bg-clip-text text-transparent text-lg font-bold"
          >
            James
          </Link>


          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page)=>(
                <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                  {page.title}
                </Link>
            ))}
          </div>
        </header>

        <main className='py-20'>{children}</main>
      </body>
    </html>
  );
}
